theme: jekyll-theme-slate
title: Welcome to Andrea Haupt’s homepage!
description: This is the portfolio page of Andrea Haupt, a front-end web-developer from the Detroit area. Feel free to bookmark this page to keep an eye on my project updates!
